# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: whiteboard.proto

import sys

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import enum_type_wrapper

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode("latin1"))
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="whiteboard.proto",
    package="Whiteboard",
    syntax="proto3",
    serialized_options=None,
    serialized_pb=_b(
        '\n\x10whiteboard.proto\x12\nWhiteboard"L\n\x0b\x42oardUpdate\x12\x10\n\x08position\x18\x01 \x01(\r\x12+\n\x06status\x18\x02 \x01(\x0e\x32\x1b.Whiteboard.BoardStatusEnum">\n\x12\x42oardUpdateRequest\x12(\n\x07updates\x18\x01 \x03(\x0b\x32\x17.Whiteboard.BoardUpdate"\x15\n\x13\x42oardUpdateResponse*6\n\x0f\x42oardStatusEnum\x12\x07\n\x03OUT\x10\x00\x12\x06\n\x02IN\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\x07\n\x03OFF\x10\x03\x32\x63\n\x11WhiteboardService\x12N\n\x0bupdateBoard\x12\x1e.Whiteboard.BoardUpdateRequest\x1a\x1f.Whiteboard.BoardUpdateResponseb\x06proto3'
    ),
)

_BOARDSTATUSENUM = _descriptor.EnumDescriptor(
    name="BoardStatusEnum",
    full_name="Whiteboard.BoardStatusEnum",
    filename=None,
    file=DESCRIPTOR,
    values=[
        _descriptor.EnumValueDescriptor(
            name="OUT", index=0, number=0, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="IN", index=1, number=1, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="ERROR", index=2, number=2, serialized_options=None, type=None
        ),
        _descriptor.EnumValueDescriptor(
            name="OFF", index=3, number=3, serialized_options=None, type=None
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=197,
    serialized_end=251,
)
_sym_db.RegisterEnumDescriptor(_BOARDSTATUSENUM)

BoardStatusEnum = enum_type_wrapper.EnumTypeWrapper(_BOARDSTATUSENUM)
OUT = 0
IN = 1
ERROR = 2
OFF = 3


_BOARDUPDATE = _descriptor.Descriptor(
    name="BoardUpdate",
    full_name="Whiteboard.BoardUpdate",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="position",
            full_name="Whiteboard.BoardUpdate.position",
            index=0,
            number=1,
            type=13,
            cpp_type=3,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
        _descriptor.FieldDescriptor(
            name="status",
            full_name="Whiteboard.BoardUpdate.status",
            index=1,
            number=2,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=32,
    serialized_end=108,
)


_BOARDUPDATEREQUEST = _descriptor.Descriptor(
    name="BoardUpdateRequest",
    full_name="Whiteboard.BoardUpdateRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name="updates",
            full_name="Whiteboard.BoardUpdateRequest.updates",
            index=0,
            number=1,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=110,
    serialized_end=172,
)


_BOARDUPDATERESPONSE = _descriptor.Descriptor(
    name="BoardUpdateResponse",
    full_name="Whiteboard.BoardUpdateResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=174,
    serialized_end=195,
)

_BOARDUPDATE.fields_by_name["status"].enum_type = _BOARDSTATUSENUM
_BOARDUPDATEREQUEST.fields_by_name["updates"].message_type = _BOARDUPDATE
DESCRIPTOR.message_types_by_name["BoardUpdate"] = _BOARDUPDATE
DESCRIPTOR.message_types_by_name["BoardUpdateRequest"] = _BOARDUPDATEREQUEST
DESCRIPTOR.message_types_by_name["BoardUpdateResponse"] = _BOARDUPDATERESPONSE
DESCRIPTOR.enum_types_by_name["BoardStatusEnum"] = _BOARDSTATUSENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BoardUpdate = _reflection.GeneratedProtocolMessageType(
    "BoardUpdate",
    (_message.Message,),
    {
        "DESCRIPTOR": _BOARDUPDATE,
        "__module__": "whiteboard_pb2"
        # @@protoc_insertion_point(class_scope:Whiteboard.BoardUpdate)
    },
)
_sym_db.RegisterMessage(BoardUpdate)

BoardUpdateRequest = _reflection.GeneratedProtocolMessageType(
    "BoardUpdateRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _BOARDUPDATEREQUEST,
        "__module__": "whiteboard_pb2"
        # @@protoc_insertion_point(class_scope:Whiteboard.BoardUpdateRequest)
    },
)
_sym_db.RegisterMessage(BoardUpdateRequest)

BoardUpdateResponse = _reflection.GeneratedProtocolMessageType(
    "BoardUpdateResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _BOARDUPDATERESPONSE,
        "__module__": "whiteboard_pb2"
        # @@protoc_insertion_point(class_scope:Whiteboard.BoardUpdateResponse)
    },
)
_sym_db.RegisterMessage(BoardUpdateResponse)


_WHITEBOARDSERVICE = _descriptor.ServiceDescriptor(
    name="WhiteboardService",
    full_name="Whiteboard.WhiteboardService",
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    serialized_start=253,
    serialized_end=352,
    methods=[
        _descriptor.MethodDescriptor(
            name="updateBoard",
            full_name="Whiteboard.WhiteboardService.updateBoard",
            index=0,
            containing_service=None,
            input_type=_BOARDUPDATEREQUEST,
            output_type=_BOARDUPDATERESPONSE,
            serialized_options=None,
        ),
    ],
)
_sym_db.RegisterServiceDescriptor(_WHITEBOARDSERVICE)

DESCRIPTOR.services_by_name["WhiteboardService"] = _WHITEBOARDSERVICE

# @@protoc_insertion_point(module_scope)
