# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import whiteboard_service.stubs.whiteboard_pb2 as whiteboard__pb2


class WhiteBoardServiceStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
        """Constructor.

    Args:
      channel: A grpc.Channel.
    """
        self.updateBoard = channel.unary_unary(
            "/whiteboard.WhiteBoardService/updateBoard",
            request_serializer=whiteboard__pb2.BoardUpdateRequest.SerializeToString,
            response_deserializer=whiteboard__pb2.BoardUpdateResponse.FromString,
        )


class WhiteBoardServiceServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def updateBoard(self, request, context):
        # missing associated documentation comment in .proto file
        pass
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_WhiteBoardServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "updateBoard": grpc.unary_unary_rpc_method_handler(
            servicer.updateBoard,
            request_deserializer=whiteboard__pb2.BoardUpdateRequest.FromString,
            response_serializer=whiteboard__pb2.BoardUpdateResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "whiteboard.WhiteBoardService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
